ASSET_ISSUER = "GCBXNC5AHNK5XDGFRAML7YUVDEDCDY4OKCUX53NQFNRF464T5I3UEA3G"
NAME = "SWINGPI"
CODE = "SWINGPI"
IMAGE = "https://swingpico.github.io/swingpi image.png"
DESCRIPTION = "SWINGPI - 1B fixed supply community token on Pi Testnet"
INFO = "https://swingpico.github.io"
